# Generated by Django 4.0.1 on 2023-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rtomanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='duplicated_rejected_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='renew_rejected_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
