# Generated by Django 4.1.5 on 2023-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rtomanagement", "0002_licence_duplicated_rejected_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learners",
            name="Gender",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="licence",
            name="Gender",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="licence",
            name="Reason_for_apply_duplicate",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="licence",
            name="Reason_for_not_renew",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vehi_reg",
            name="Gender",
            field=models.CharField(max_length=30),
        ),
    ]
